name: CI-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run unit testing'

jobs:
  pytest:
    #name: unit testing
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest]

    steps:
    - name: Checkout simple_functions
      uses: actions/checkout@v2

    - name: Set test directory
      run : |
        echo "::set-env name=TESTS::tests/"

    - name: Install dependencies on MacOS (1)
      if: matrix.os == 'macos-latest'
      run: |
        curl -O https://bootstrap.pypa.io/ez_setup.py
        python3 ez_setup.py
        curl -O https://bootstrap.pypa.io/get-pip.py
        python3 get-pip.py

    - name: Install dependencies (1)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get install python3-setuptools -y

    - name: Install dependencies (2)
      run: |
        pip3 install --upgrade pip
        pip3 install -e .
        pip3 install -r requirements.txt

    - name: Set a run prefix
      run : |
        echo "::set-env name=RUN::python3 -m"

    - name: Test with pytest
      run: |
        $RUN pytest $TESTS
